### ISSUE TITLE
How to page down?

### ISSUE THREAD

**Issue by aihy** [amix/vimrc#476] opened 2018-11-01 09:20 UTC
I used <C-f> <C-b> for page down and up, how to do that now? Thank you very much!

**Comment by shan23** [comment] 2018-11-29 23:13
`Ctrl + D`, `Ctrl + U`

**Comment by al03** [comment] 2019-01-17 08:14
How to disable the scroll animation?

**Comment by stoneboy100200** [comment] 2019-08-18 03:32
how to disable the scroll animation??????????????????

**Comment by Arnie97** [comment] 2019-08-23 18:36
See #452 @al03 @stoneboy100200

**Comment by amix** [comment] 2019-11-17 18:56
A duplicate of https://github.com/amix/vimrc/issues/452

**Closed by amix** 2019-11-17 18:56 UTC
